name: "Test Pull Request"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - 'feat/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3
      - name: Lint functions
        run: |
          cd functions
          npm run lint
      - name: Lint packages
        run: |
          pwd
