name: "Test Pull Request"

on:
  pull_request:
    branches:
      - "main"

jobs:
  lint-functions:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Lint Functions"
          cd functions
          npm ci
          npm run lint
      - run: |
          echo "Lint Postman"
          cd postman
          npm ci
          npm run lint
      - run: |
          echo "Build Functions"
          cd functions
          npm run build
      - run: |
          echo "Build Postman"
          cd postman
          npm run build
      - run: |
          echo "Install Firebase"
          npm install -g firebase-tools
      - run: |
          echo "Start Firebase Emulator"
          firebase emulators:start &
      - run: |
          echo "Wait for Firebase Emulator"
          node postman/wait.js
      - run: |
          echo "Test"
          cd postman
          npm run test
