name: "Test Pull Request"

#on:
#  pull_request:
#    branches:
#      - "main"
on:
  push:
    branches:
      - 'feat/**'

jobs:
  lint-functions:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Lint Functions"
          cd functions
          npm ci
          npm run lint
      - run: |
          echo "Lint Postman"
          cd postman
          npm ci
          npm run lint
      - run: |
          echo "Build Functions"
          cd functions
          npm run build
      - run: |
          echo "Build Postman"
          cd postman
          npm run build
      - run: |
          echo "Install Firebase"
          npm install -g firebase-tools
      - run: |
          echo "Start Firebase Emulator"
          firebase emulators:start &
      - run: |
          echo "Wait for Firebase Emulator"
          wait() {
            TRIES=1
            READY=false
            while ["$READY" != "true"];
            do
              PROJECT_ID=$(curl -sk 'http://localhost:4000/api/config' jq -r .projectId)
              if ["$PROJECT_ID" = "auth-emulator-example"]; then
                echo "Firebase Emulator is ready"
                READY=true
              else
                echo "Wait..."
                sleep 10
                ((TRIES=TRIES+1))
              fi
              if [ "$TRIES" -qt 30 ]; then
                echo "Firebase Emulator is not ready"
                exit 1
              fi
            done
          }
          wait
      - run: |
          echo "Test"
          cd postman
          npm run test

# jobs:
#   lint-functions:
#     runs-on: ubuntu-latest
#     name: Lint Functions
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#           cache-dependency-path: functions/package-lock.json
#       - run: |
#           cd postman
#           npm ci
#           npm run lint

#   lint-postman:
#     runs-on: ubuntu-latest
#     name: Lint Postman
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#           cache-dependency-path: postman/package-lock.json
#       - run: |
#           cd postman
#           npm ci
#           npm run lint

#   build-functions:
#     runs-on: ubuntu-latest
#     name: Build Functions
#     needs: lint-functions
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#           cache-dependency-path: functions/package-lock.json
#       - run: |
#           cd postman
#           npm ci
#           npm run build

#   build-postman:
#     runs-on: ubuntu-latest
#     name: Build Postman
#     needs: lint-postman
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#           cache-dependency-path: postman/package-lock.json
#       - run: |
#           cd postman
#           npm ci
#           npm run build