name: "Test Pull Request"

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: pr-pipeline
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Lint Functions
        run: |
          cd functions
          npm ci
          npm run lint
      - name: Lint Postman
        run: |
          cd postman
          npm ci
          npm run lint
      - name: "Build Functions"
        run: |
          cd functions
          npm run build
      - name: Build Postman
        run: |
          cd postman
          npm run build
      - name: Install Firebase
        run: |
          cd utils
          chmod +x firebase-version.sh
          export FIREBASE_VERSION="$(./firebase-version.sh)"
          echo "Firebase version: $FIREBASE_VERSION"
          npm install -g firebase-tools@$FIREBASE_VERSION
          echo "Verify installed Firebase:"
          firebase --version
      - name: Start Firebase Emulator
        run: |
          firebase emulators:start &
      - name: Wait for Firebase Emulator
        run: |
          chmod +x utils/wait.sh
          ./utils/wait.sh
      - name: Test
        run: |
          cd postman
          npm run test
  auto-merge:
    needs: test
    name: Auto Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
